-- BAI 1
SELECT NAME FROM CITY 
WHERE COUNTRYCODE = 'USA'
AND POPULATION 

-- BAI 2
SELECT * FROM CITY 
WHERE COUNTRYCODE = 'JPN';

-- BAI 3
SELECT CITY, STATE FROM STATION;

--BAI 4
SELECT DISTINCT CITY
FROM STATION
WHERE CITY LIKE 'A%' 
   OR CITY LIKE 'E%'
   OR CITY LIKE 'I%'
   OR CITY LIKE 'O%'
   OR CITY LIKE 'U%';

--BAI 5
SELECT DISTINCT CITY
FROM STATION
WHERE CITY LIKE '%A' 
   OR CITY LIKE '%E'
   OR CITY LIKE '%I'
   OR CITY LIKE '%O'
   OR CITY LIKE '%U';

--BAI 6
SELECT DISTINCT CITY
FROM STATION
WHERE CITY NOT LIKE 'A%' 
  AND CITY NOT LIKE 'E%'
  AND CITY NOT LIKE 'I%'
  AND CITY NOT LIKE 'O%'
  AND CITY NOT LIKE 'U%';

--BAI 7
SELECT NAME
FROM EMPLOYEE
ORDER BY NAME ASC;

--BAI 8
SELECT NAME FROM EMPLOYEE
WHERE  SALARY >2000
AND MONTHS <10;

--BAI 9
SELECT PRODUCT_ID FROM PRODUCTS
WHERE LOW_FATS = RECYCLABLE;

--BAI 10 
SELECT NAME
FROM CUSTOMER
WHERE REFEREE_ID != 2
   OR REFEREE_ID IS NULL;

--BAI 11
SELECT NAME, POPULATION, AREA FROM WORLD
WHERE AREA >= 3000000
OR POPULATION >= 25000000 ;

--BAI 12
SELECT DISTINCT author_id AS id
FROM Views
WHERE author_id = viewer_id
ORDER BY author_id;

--BAI 13
SELECT PART, ASSEMBLY_STEP
FROM PARTS_ASSEMBY
WHERE FINISH_DATE IS NULL;

--BAI 14 
SELECT *
FROM LYFT_DRIVERS
WHERE YEARY_SALARY  <= 30000
   OR YEARY_SALARY >= 70000;

--BAI 15
SELECT ADVERTISING_CHANNEL 
FROM  UBER_ADVERTISING
WHERE year = 2019
  AND MONEY_SPENT > 100000;



